### ISSUE TITLE
Fade option doesn't work

### ISSUE THREAD

**Issue by Daithi** [solstice23/bar-overlay-for-osu#2]
No matter how many times I enable/disable the option or which order I open gosumemory, osu, or StreamLabs, the overlay never fades like it does in the examples.

**Comment by solstice23** [comment]
Already been fixed in https://github.com/solstice23/osu-bar-overlay/commit/7e9496015f9b78abb4138f54c89b1d502e4c1a32, but I forgot to create a release tag. Now you can download the latest release at https://github.com/solstice23/osu-bar-overlay/releases/tag/1.1.
